require 'set'
require 'values'

require_relative './game_of_life/world.rb'
require_relative './game_of_life/coordinate_2d.rb'
require_relative './game_of_life/coordinate_1d.rb'
require_relative './game_of_life/conway_rules.rb'
require_relative './game_of_life/wolfram_rules.rb'
require_relative './game_of_life/user_interface_2d.rb'
require_relative './game_of_life/user_interface_1d.rb'
require_relative './game_of_life/ruleset_world_builder.rb'
